---
  - type: java\.time\.LocalDate
    specAsParameter:
      - type: string
        format: date
  - type: java\.time\.LocalDateTime
    specAsParameter:
      - type: string
        format: date-time
  - type: java\.time\.OffsetDate
    specAsParameter:
      - type: string
        format: date
  - type: java\.time\.OffsetDateTime
    specAsParameter:
      - type: string
        format: date-time
